name: menu_crewler

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.x
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
     
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential libffi-dev
          
      - name: Run Python script
        run: python dinner_menu.py

      - name: Commits
        run: |
          git config --local user.email "wls5258@naver.com"
          git config --local user.name "202116302" # 커밋에 포함될 이름
          git add output/jinsu_menu.csv
          git commit -m "Auto - Update data with Scraping" # 커밋 메세지
          
      - name: Push
        uses: ad-m/github-push-action@master
        with:
        branch: 'master'
        github_token: $


