name: send menu (email)

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  run-code:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential libffi-dev

      - name: Install system dependenciesadd
        run: sudo apt-get install libffi-dev libssl-dev
     
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run Python script
        run: python dinner_menu.py
        env:
            pythonLocation: /opt/hostedtoolcache/Python/3.11.3/x64
            LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.11.3/x64/lib
